// Only import purchaseService to avoid circular dependency
const purchaseService = require("./purchase.service");

/**
 * Unified service to handle payment callbacks for both tickets and purchases
 * Now only handles purchases - tickets are auto-generated by purchase.service
 */

const handleUnifiedCallback = async (callbackData) => {
  try {
    console.log("🔄 Processing unified payment callback...");
    console.log("Callback data:", JSON.stringify(callbackData, null, 2));

    // Validate callback data
    if (!callbackData || typeof callbackData !== "object") {
      throw new Error("Invalid callback data");
    }

    // Extract relevant information from the callback
    const {
      id,
      external_id,
      status,
      amount,
      paid_amount,
      paid_at,
      payer_email,
      payment_method,
      payment_channel,
    } = callbackData;

    // Validate required fields
    if (!id || !external_id || !status) {
      throw new Error("Missing required fields in callback data");
    }

    // Handle Xendit test payload
    if (external_id === "invoice_123124123") {
      console.log("Received Xendit Test Payload. Returning success.");
      return {
        purchase_id: "test-purchase-id",
        status: "paid",
        message: "Test payload processed successfully",
        invoice_id: id,
        external_id: external_id,
      };
    }

    // All callbacks now go through purchase flow
    // Tickets are auto-generated when ticket products are purchased
    console.log("🛒 Processing as purchase callback...");
    return await purchaseService.handleInvoiceCallback(callbackData);
  } catch (error) {
    console.error("Failed to handle unified callback:", error);
    throw new Error("Failed to handle unified callback: " + error.message);
  }
};

module.exports = {
  handleUnifiedCallback,
};
